Removing unused package filter.
I noticed in the travis output the following
Error: Ignoring unknown package filter 'extra-android-support'
so its obviously not being used so I have removed it.